### ISSUE TITLE
Dai not working. 

### ISSUE THREAD

**Issue by Vamsee30** [ryanio/truffle-mint-dai#7]
The Dai user address does not have any Dai left. So once I changed that, the errors go away.
But when I check my balance, I only receive Sai, but no Dai.

**Comment by ryanio** [comment]
thanks for reporting, let me look into this

**Comment by 101pm** [comment]
Yeah, this is happening for me too.

**Comment by 101pm** [comment]
Has anyone come up with a solution so far?

**Comment by ryanio** [comment]
I have an idea to fix this by dynamically querying through recent event logs for large holders to use for the examples.

I will try to push some code to the repo today and will give an update here.

I might have to also remove the SAI example and just keep the new DAI (MCD, Multi-Collateral Dai) since SAI will be going away soon.

**Comment by Vamsee30** [comment]
If anyone is stuck I ended up using hard-hat which allows me to fork a chain and then emulate any account. So I just emulated an account with Dai and sent it to myself.

**Comment by 101pm** [comment]
@Vamsee30, Awsome, I'll try that. @ryanio Thanks for responding and trying to fix it 👍.

**Comment by ryanio** [comment]
Ok sorry for the delay but this should be working now, try checking out the latest version of `master` on the repository and following the updated README.

I also set up a [Github Action](https://github.com/ryanio/truffle-mint-dai/actions) as a sanity check for the future in case it breaks again :)

Please let me know if you have any further questions!

**Comment by ryanio** [comment]
I will close this issue for now but please feel free to continue discussion here or open a new issue.
